# rs_context.h function
export rs2_create_context
export rs2_delete_context
export rs2_set_devices_changed_callback_cpp
export rs2_set_devices_changed_callback
export rs2_context_add_device
export rs2_context_remove_device
export rs2_query_devices
export rs2_create_device_hub
export rs2_delete_device_hub
export rs2_device_hub_wait_for_device
export rs2_device_hub_is_device_connected
# rs_context.h macro
export RS2_PRODUCT_LINE_ANY
export RS2_PRODUCT_LINE_ANY_INTEL
export RS2_PRODUCT_LINE_NON_INTEL
export RS2_PRODUCT_LINE_D400
export RS2_PRODUCT_LINE_SR300


# rs_device.h function
export rs2_get_device_count
export rs2_delete_device_list
export rs2_device_list_contains
export rs2_create_device
export rs2_delete_device
export rs2_get_device_info
export rs2_supports_device_info
export rs2_hardware_reset
export rs2_send_and_receive_raw_data
export rs2_is_device_extendable_to
export rs2_query_sensors
export rs2_loopback_enable
export rs2_loopback_disable
export rs2_loopback_is_enabled
export rs2_connect_tm2_controller
export rs2_disconnect_tm2_controller


# rs_frame.h function
export rs2_timestamp_domain_to_string
export rs2_frame_metadata_to_string
export rs2_frame_metadata_value_to_string
export rs2_get_frame_metadata
export rs2_supports_frame_metadata
export rs2_get_frame_timestamp_domain
export rs2_get_frame_timestamp
export rs2_get_frame_number
export rs2_get_frame_data
export rs2_get_frame_width
export rs2_get_frame_height
export rs2_get_frame_stride_in_bytes
export rs2_get_frame_bits_per_pixel
export rs2_frame_add_ref
export rs2_release_frame
export rs2_keep_frame
export rs2_get_frame_vertices
export rs2_export_to_ply
export rs2_get_frame_texture_coordinates
export rs2_get_frame_points_count
export rs2_get_frame_stream_profile
export rs2_is_frame_extendable_to
export rs2_allocate_synthetic_video_frame
export rs2_allocate_composite_frame
export rs2_extract_frame
export rs2_embedded_frames_count
export rs2_synthetic_frame_ready
export rs2_pose_frame_get_pose_data
# rs_frame.h enum
export rs2_timestamp_domain
export RS2_TIMESTAMP_DOMAIN_HARDWARE_CLOCK
export RS2_TIMESTAMP_DOMAIN_SYSTEM_TIME
export RS2_TIMESTAMP_DOMAIN_COUNT
export rs2_frame_metadata_value
export rs2_frame_metadata_value
export RS2_FRAME_METADATA_FRAME_COUNTER
export RS2_FRAME_METADATA_FRAME_TIMESTAMP
export RS2_FRAME_METADATA_SENSOR_TIMESTAMP
export RS2_FRAME_METADATA_ACTUAL_EXPOSURE
export RS2_FRAME_METADATA_GAIN_LEVEL
export RS2_FRAME_METADATA_AUTO_EXPOSURE
export RS2_FRAME_METADATA_WHITE_BALANCE
export RS2_FRAME_METADATA_TIME_OF_ARRIVAL
export RS2_FRAME_METADATA_TEMPERATURE
export RS2_FRAME_METADATA_BACKEND_TIMESTAMP
export RS2_FRAME_METADATA_ACTUAL_FPS
export RS2_FRAME_METADATA_FRAME_LASER_POWER
export RS2_FRAME_METADATA_FRAME_LASER_POWER_MODE
export RS2_FRAME_METADATA_EXPOSURE_PRIORITY
export RS2_FRAME_METADATA_EXPOSURE_ROI_LEFT
export RS2_FRAME_METADATA_EXPOSURE_ROI_RIGHT
export RS2_FRAME_METADATA_EXPOSURE_ROI_TOP
export RS2_FRAME_METADATA_EXPOSURE_ROI_BOTTOM
export RS2_FRAME_METADATA_BRIGHTNESS
export RS2_FRAME_METADATA_CONTRAST
export RS2_FRAME_METADATA_SATURATION
export RS2_FRAME_METADATA_SHARPNESS
export RS2_FRAME_METADATA_AUTO_WHITE_BALANCE_TEMPERATURE
export RS2_FRAME_METADATA_BACKLIGHT_COMPENSATION
export RS2_FRAME_METADATA_HUE
export RS2_FRAME_METADATA_GAMMA
export RS2_FRAME_METADATA_MANUAL_WHITE_BALANCE
export RS2_FRAME_METADATA_POWER_LINE_FREQUENCY
export RS2_FRAME_METADATA_LOW_LIGHT_COMPENSATION
export RS2_FRAME_METADATA_COUNT
# rs_frame.h struct
export rs2_vertex
export rs2_pixel
export rs2_vector
export rs2_quaternion
export rs2_pose


# rs_internal.h function
export rs2_create_recording_context
export rs2_create_mock_context
export rs2_create_mock_context_versioned
export rs2_create_software_device
export rs2_software_device_add_sensor
export rs2_software_sensor_on_video_frame
export rs2_software_sensor_set_metadata
export rs2_software_device_create_matcher
export rs2_software_sensor_add_video_stream
export rs2_software_sensor_add_read_only_option
export rs2_software_sensor_update_read_only_option
# rs_internal.h struct
export rs2_video_stream
export rs2_software_video_frame
# rs_internal.h enum
export rs2_recording_mode
export RS2_RECORDING_MODE_BLANK_FRAMES
export RS2_RECORDING_MODE_COMPRESSED
export RS2_RECORDING_MODE_BEST_QUALITY
export RS2_RECORDING_MODE_COUNT
export rs2_recording_mode
export RS2_RECORDING_MODE_BLANK_FRAMES
export RS2_RECORDING_MODE_COMPRESSED
export RS2_RECORDING_MODE_BEST_QUALITY
export RS2_RECORDING_MODE_COUNT


# rs_option.h function
export rs2_option_to_string
export rs2_sr300_visual_preset_to_string
export rs2_rs400_visual_preset_to_string
export rs2_is_option_read_only
export rs2_get_option
export rs2_set_option
export rs2_supports_option
export rs2_get_option_range
export rs2_get_option_description
export rs2_get_option_value_description
# rs_option.h enums
export rs2_option
export RS2_OPTION_BACKLIGHT_COMPENSATION
export RS2_OPTION_BRIGHTNESS
export RS2_OPTION_CONTRAST
export RS2_OPTION_EXPOSURE
export RS2_OPTION_GAIN
export RS2_OPTION_GAMMA
export RS2_OPTION_HUE
export RS2_OPTION_SATURATION
export RS2_OPTION_SHARPNESS
export RS2_OPTION_WHITE_BALANCE
export RS2_OPTION_ENABLE_AUTO_EXPOSURE
export RS2_OPTION_ENABLE_AUTO_WHITE_BALANCE
export RS2_OPTION_VISUAL_PRESET
export RS2_OPTION_LASER_POWER
export RS2_OPTION_ACCURACY
export RS2_OPTION_MOTION_RANGE
export RS2_OPTION_FILTER_OPTION
export RS2_OPTION_CONFIDENCE_THRESHOLD
export RS2_OPTION_EMITTER_ENABLED
export RS2_OPTION_FRAMES_QUEUE_SIZE
export RS2_OPTION_TOTAL_FRAME_DROPS
export RS2_OPTION_AUTO_EXPOSURE_MODE
export RS2_OPTION_POWER_LINE_FREQUENCY
export RS2_OPTION_ASIC_TEMPERATURE
export RS2_OPTION_ERROR_POLLING_ENABLED
export RS2_OPTION_PROJECTOR_TEMPERATURE
export RS2_OPTION_OUTPUT_TRIGGER_ENABLED
export RS2_OPTION_MOTION_MODULE_TEMPERATURE
export RS2_OPTION_DEPTH_UNITS
export RS2_OPTION_ENABLE_MOTION_CORRECTION
export RS2_OPTION_AUTO_EXPOSURE_PRIORITY
export RS2_OPTION_COLOR_SCHEME
export RS2_OPTION_HISTOGRAM_EQUALIZATION_ENABLED
export RS2_OPTION_MIN_DISTANCE
export RS2_OPTION_MAX_DISTANCE
export RS2_OPTION_TEXTURE_SOURCE
export RS2_OPTION_FILTER_MAGNITUDE
export RS2_OPTION_FILTER_SMOOTH_ALPHA
export RS2_OPTION_FILTER_SMOOTH_DELTA
export RS2_OPTION_HOLES_FILL
export RS2_OPTION_STEREO_BASELINE
export RS2_OPTION_AUTO_EXPOSURE_CONVERGE_STEP
export RS2_OPTION_INTER_CAM_SYNC_MODE
export RS2_OPTION_COUNT
export rs2_sr300_visual_preset
export RS2_SR300_VISUAL_PRESET_SHORT_RANGE
export RS2_SR300_VISUAL_PRESET_LONG_RANGE
export RS2_SR300_VISUAL_PRESET_BACKGROUND_SEGMENTATION
export RS2_SR300_VISUAL_PRESET_GESTURE_RECOGNITION
export RS2_SR300_VISUAL_PRESET_OBJECT_SCANNING
export RS2_SR300_VISUAL_PRESET_FACE_ANALYTICS
export RS2_SR300_VISUAL_PRESET_FACE_LOGIN
export RS2_SR300_VISUAL_PRESET_GR_CURSOR
export RS2_SR300_VISUAL_PRESET_DEFAULT
export RS2_SR300_VISUAL_PRESET_MID_RANGE
export RS2_SR300_VISUAL_PRESET_IR_ONLY
export RS2_SR300_VISUAL_PRESET_COUNT
export rs2_rs400_visual_preset
export RS2_RS400_VISUAL_PRESET_CUSTOM
export RS2_RS400_VISUAL_PRESET_DEFAULT
export RS2_RS400_VISUAL_PRESET_HAND
export RS2_RS400_VISUAL_PRESET_HIGH_ACCURACY
export RS2_RS400_VISUAL_PRESET_HIGH_DENSITY
export RS2_RS400_VISUAL_PRESET_MEDIUM_DENSITY
export RS2_RS400_VISUAL_PRESET_REMOVE_IR_PATTERN
export RS2_RS400_VISUAL_PRESET_COUNT


# rs_pipeline.h function
export rs2_create_pipeline
export rs2_pipeline_stop
export rs2_pipeline_wait_for_frames
export rs2_pipeline_poll_for_frames
export rs2_delete_pipeline
export rs2_pipeline_start
export rs2_pipeline_start_with_config
export rs2_pipeline_get_active_profile
export rs2_pipeline_profile_get_device
export rs2_pipeline_profile_get_streams
export rs2_delete_pipeline_profile
export rs2_create_config
export rs2_delete_config
export rs2_config_enable_stream
export rs2_config_enable_all_stream
export rs2_config_enable_device
export rs2_config_enable_device_from_file
export rs2_config_enable_device_from_file_repeat_option
export rs2_config_enable_record_to_file
export rs2_config_disable_stream
export rs2_config_disable_indexed_stream
export rs2_config_disable_all_streams
export rs2_config_resolve
export rs2_config_can_resolve


# rs_processing.h function
export rs2_create_colorizer
export rs2_create_sync_processing_block
export rs2_create_pointcloud
export rs2_create_processing_block
export rs2_create_processing_block_fptr
export rs2_start_processing
export rs2_start_processing_fptr
export rs2_start_processing_queue
export rs2_process_frame
export rs2_delete_processing_block
export rs2_create_frame_queue
export rs2_delete_frame_queue
export rs2_wait_for_frame
export rs2_poll_for_frame
export rs2_try_wait_for_frame
export rs2_enqueue_frame
export rs2_create_align
export rs2_create_decimation_filter_block
export rs2_create_temporal_filter_block
export rs2_create_spatial_filter_block
export rs2_create_disparity_transform_block
export rs2_create_hole_filling_filter_block


# rs_record_playback.h function
export rs2_playback_status_to_string
export rs2_create_record_device
export rs2_record_device_pause
export rs2_record_device_resume
export rs2_record_device_filename
export rs2_create_playback_device
export rs2_playback_device_get_file_path
export rs2_playback_get_duration
export rs2_playback_seek
export rs2_playback_get_position
export rs2_playback_device_resume
export rs2_playback_device_pause
export rs2_playback_device_set_real_time
export rs2_playback_device_is_real_time
export rs2_playback_device_set_status_changed_callback
export rs2_playback_device_get_current_status
export rs2_playback_device_set_playback_speed
export rs2_playback_device_stop
# rs_record_playback.h enum
export rs2_playback_status
export RS2_PLAYBACK_STATUS_UNKNOWN
export RS2_PLAYBACK_STATUS_PLAYING
export RS2_PLAYBACK_STATUS_PAUSED
export RS2_PLAYBACK_STATUS_STOPPED
export RS2_PLAYBACK_STATUS_COUNT


# rs_sensor.h function
export rs2_camera_info_to_string
export rs2_stream_to_string
export rs2_format_to_string
export rs2_delete_sensor_list
export rs2_get_sensors_count
export rs2_delete_sensor
export rs2_create_sensor
export rs2_create_device_from_sensor
export rs2_get_sensor_info
export rs2_supports_sensor_info
export rs2_is_sensor_extendable_to
export rs2_get_depth_scale
export rs2_depth_stereo_frame_get_baseline
export rs2_set_region_of_interest
export rs2_get_region_of_interest
export rs2_open
export rs2_open_multiple
export rs2_close
export rs2_start
export rs2_start_cpp
export rs2_start_queue
export rs2_stop
export rs2_set_notifications_callback
export rs2_set_notifications_callback_cpp
export rs2_get_notification_description
export rs2_get_notification_timestamp
export rs2_get_notification_severity
export rs2_get_notification_category
export rs2_get_notification_serialized_data
export rs2_get_stream_profiles
export rs2_get_stream_profile
export rs2_get_stream_profile_data
export rs2_set_stream_profile_data
export rs2_clone_stream_profile
export rs2_delete_stream_profile
export rs2_stream_profile_is
export rs2_get_video_stream_resolution
export rs2_get_motion_intrinsics
export rs2_is_stream_profile_default
export rs2_get_stream_profiles_count
export rs2_delete_stream_profiles_list
export rs2_get_extrinsics
export rs2_register_extrinsics
export rs2_get_video_stream_intrinsics
# rs_sensor.h enum
export rs2_format
export RS2_FORMAT_ANY
export RS2_FORMAT_Z16
export RS2_FORMAT_DISPARITY16
export RS2_FORMAT_XYZ32F
export RS2_FORMAT_YUYV
export RS2_FORMAT_RGB8
export RS2_FORMAT_BGR8
export RS2_FORMAT_RGBA8
export RS2_FORMAT_BGRA8
export RS2_FORMAT_Y8
export RS2_FORMAT_Y16
export RS2_FORMAT_RAW10
export RS2_FORMAT_RAW16
export RS2_FORMAT_RAW8
export RS2_FORMAT_UYVY
export RS2_FORMAT_MOTION_RAW
export RS2_FORMAT_MOTION_XYZ32F
export RS2_FORMAT_GPIO_RAW
export RS2_FORMAT_6DOF
export RS2_FORMAT_DISPARITY32
export RS2_FORMAT_COUNT
export rs2_camera_info
export RS2_CAMERA_INFO_NAME
export RS2_CAMERA_INFO_SERIAL_NUMBER
export RS2_CAMERA_INFO_FIRMWARE_VERSION
export RS2_CAMERA_INFO_RECOMMENDED_FIRMWARE_VERSION
export RS2_CAMERA_INFO_PHYSICAL_PORT
export RS2_CAMERA_INFO_DEBUG_OP_CODE
export RS2_CAMERA_INFO_ADVANCED_MODE
export RS2_CAMERA_INFO_PRODUCT_ID
export RS2_CAMERA_INFO_CAMERA_LOCKED
export RS2_CAMERA_INFO_USB_TYPE_DESCRIPTOR
export RS2_CAMERA_INFO_COUNT
export rs2_stream
export RS2_STREAM_ANY
export RS2_STREAM_DEPTH
export RS2_STREAM_COLOR
export RS2_STREAM_INFRARED
export RS2_STREAM_FISHEYE
export RS2_STREAM_GYRO
export RS2_STREAM_ACCEL
export RS2_STREAM_GPIO
export RS2_STREAM_POSE
export RS2_STREAM_CONFIDENCE
export RS2_STREAM_COUNT
# rs_sensor.h struct
export rs2_extrinsics


# rs_types.h function
export rs2_notification_category_to_string
export rs2_exception_type_to_string
export rs2_distortion_to_string
export rs2_log_severity_to_string
export rs2_extension_type_to_string
export rs2_extension_to_string
export rs2_get_librealsense_exception_type
export rs2_get_failed_function
export rs2_get_failed_args
export rs2_get_error_message
export rs2_free_error
# rs_types.h enum
export rs2_matchers
export RS2_MATCHER_DI
export RS2_MATCHER_DI_C
export RS2_MATCHER_DLR_C
export RS2_MATCHER_DLR
export RS2_MATCHER_DEFAULT
export RS2_MATCHER_COUNT
export rs2_extension
export RS2_EXTENSION_UNKNOWN
export RS2_EXTENSION_DEBUG
export RS2_EXTENSION_INFO
export RS2_EXTENSION_MOTION
export RS2_EXTENSION_OPTIONS
export RS2_EXTENSION_VIDEO
export RS2_EXTENSION_ROI
export RS2_EXTENSION_DEPTH_SENSOR
export RS2_EXTENSION_VIDEO_FRAME
export RS2_EXTENSION_MOTION_FRAME
export RS2_EXTENSION_COMPOSITE_FRAME
export RS2_EXTENSION_POINTS
export RS2_EXTENSION_DEPTH_FRAME
export RS2_EXTENSION_ADVANCED_MODE
export RS2_EXTENSION_RECORD
export RS2_EXTENSION_VIDEO_PROFILE
export RS2_EXTENSION_PLAYBACK
export RS2_EXTENSION_DEPTH_STEREO_SENSOR
export RS2_EXTENSION_DISPARITY_FRAME
export RS2_EXTENSION_MOTION_PROFILE
export RS2_EXTENSION_POSE_FRAME
export RS2_EXTENSION_POSE_PROFILE
export RS2_EXTENSION_TM2
export RS2_EXTENSION_SOFTWARE_DEVICE
export RS2_EXTENSION_SOFTWARE_SENSOR
export RS2_EXTENSION_COUNT
export rs2_log_severity
export RS2_LOG_SEVERITY_DEBUG
export RS2_LOG_SEVERITY_INFO
export RS2_LOG_SEVERITY_WARN
export RS2_LOG_SEVERITY_ERROR
export RS2_LOG_SEVERITY_FATAL
export RS2_LOG_SEVERITY_NONE
export RS2_LOG_SEVERITY_COUNT
export rs2_distortion
export RS2_DISTORTION_NONE
export RS2_DISTORTION_MODIFIED_BROWN_CONRADY
export RS2_DISTORTION_INVERSE_BROWN_CONRADY
export RS2_DISTORTION_FTHETA
export RS2_DISTORTION_BROWN_CONRADY
export RS2_DISTORTION_COUNT
export rs2_exception_type
export RS2_EXCEPTION_TYPE_UNKNOWN
export RS2_EXCEPTION_TYPE_CAMERA_DISCONNECTED
export RS2_EXCEPTION_TYPE_BACKEND
export RS2_EXCEPTION_TYPE_INVALID_VALUE
export RS2_EXCEPTION_TYPE_WRONG_API_CALL_SEQUENCE
export RS2_EXCEPTION_TYPE_NOT_IMPLEMENTED
export RS2_EXCEPTION_TYPE_DEVICE_IN_RECOVERY_MODE
export RS2_EXCEPTION_TYPE_IO
export RS2_EXCEPTION_TYPE_COUNT
export rs2_notification_category
export RS2_NOTIFICATION_CATEGORY_FRAMES_TIMEOUT
export RS2_NOTIFICATION_CATEGORY_FRAME_CORRUPTED
export RS2_NOTIFICATION_CATEGORY_HARDWARE_ERROR
export RS2_NOTIFICATION_CATEGORY_HARDWARE_EVENT
export RS2_NOTIFICATION_CATEGORY_UNKNOWN_ERROR
export RS2_NOTIFICATION_CATEGORY_FIRMWARE_UPDATE_RECOMMENDED
export RS2_NOTIFICATION_CATEGORY_COUNT
# rs_types.h struct
export rs2_intrinsics
export rs2_motion_device_intrinsic
export rs2_device_info
export rs2_device
export rs2_error
export rs2_raw_data_buffer
export rs2_frame
export rs2_frame_queue
export rs2_pipeline
export rs2_pipeline_profile
export rs2_config
export rs2_device_list
export rs2_stream_profile_list
export rs2_stream_profile
export rs2_frame_callback
export rs2_log_callback
export rs2_syncer
export rs2_device_serializer
export rs2_source
export rs2_processing_block
export rs2_frame_processor_callback
export rs2_playback_status_changed_callback
export rs2_context
export rs2_device_hub
export rs2_sensor_list
export rs2_sensor
export rs2_options
export rs2_devices_changed_callback
export rs2_notification
export rs2_notifications_callback
export rs2_notification_callback_ptr
export rs2_devices_changed_callback_ptr
export rs2_frame_callback_ptr
export rs2_frame_processor_callback_ptr
export rs2_time_t
export rs2_metadata_type


# rs.h function
export rs2_get_raw_data_size
export rs2_delete_raw_data
export rs2_get_raw_data
export rs2_get_api_version
export rs2_log_to_console
export rs2_log_to_file
export rs2_log
export rs2_depth_frame_get_distance
export rs2_get_time
# rs.h macro
export RS2_API_MAJOR_VERSION
export RS2_API_MINOR_VERSION
export RS2_API_PATCH_VERSION
export RS2_API_BUILD_VERSION


# rs_advanced_mode.h function
export rs2_toggle_advanced_mode
export rs2_is_enabled
export rs2_set_depth_control
export rs2_get_depth_control
export rs2_set_rsm
export rs2_get_rsm
export rs2_set_rau_support_vector_control
export rs2_get_rau_support_vector_control
export rs2_set_color_control
export rs2_get_color_control
export rs2_set_rau_thresholds_control
export rs2_get_rau_thresholds_control
export rs2_set_slo_color_thresholds_control
export rs2_get_slo_color_thresholds_control
export rs2_set_slo_penalty_control
export rs2_get_slo_penalty_control
export rs2_set_hdad
export rs2_get_hdad
export rs2_set_color_correction
export rs2_get_color_correction
export rs2_set_depth_table
export rs2_get_depth_table
export rs2_set_ae_control
export rs2_get_ae_control
export rs2_set_census
export rs2_get_census
export rs2_load_json
export rs2_serialize_json


# others
export rs2_project_point_to_pixel
export rs2_deproject_pixel_to_point
export rs2_transform_point_to_point
export rs2_fov
export rs2_playback_status_changed_callback_ptr
export STDepthControlGroup
export STRsm
export STRauSupportVectorControl
export STColorControl
export STRauColorThresholdsControl
export STSloColorThresholdsControl
export STSloPenaltyControl
export STHdad
export STColorCorrection
export STAEControl
export STDepthTableControl
export STCensusRadius





















export rs2_recording_mode
export RS2_RECORDING_MODE_BLANK_FRAMES
export RS2_RECORDING_MODE_COMPRESSED
export RS2_RECORDING_MODE_BEST_QUALITY
export RS2_RECORDING_MODE_COUNT
